### PR TITLE
Make use of TR-064 API

### PR DESCRIPTION
**Pull request by Jopyth**
Deals with #11 .

There are some problems left, repeated access to the FritzBox prevents further logins. Probably due to a bug in the [underlying library](https://github.com/hendrikw01/tr-064). I am not sure how to fix it. But so far it works if your do not restart your mirror very often. I think once or twice per day is fine.

### CODE REVIEW

**Comment by paviro** [comment]
Thanks! Is it optional to use?

**Comment by Jopyth** [comment]
Yes, if no password is entered (default), everything stays the same. Do you think that is clear enough in the [Readme](https://github.com/Jopyth/MMM-FRITZ-Box-Callmonitor/blob/200397289f63a6b6a5e130c4985fdd43566d3878/README.md)?

**Comment by Jopyth** [comment]
I made some more changes to the readme, I think it should be pretty clear also for anyone who just starts using this module.

**Comment by paviro** [comment]
Could you please add your new dependencies to the README? :)

**Pull request merged**
